name: Kompilator Cheat-Clienta Fabric
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie plików projektu
        uses: actions/checkout@v4

      - name: Konfiguracja Javy 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Instalacja oficjalnego Gradle Wrapper
        run: gradle wrapper --gradle-version 8.11.1

      - name: Kompilacja pliku .JAR (Budowanie cheat-clienta)
        run: |
          chmod +x gradlew
          ./gradlew build --no-daemon

      - name: Przesyłanie gotowego cheata na dysk
        uses: actions/upload-artifact@v4
        with:
          name: Tworcy-Cheat-Client-JAR
          path: build/libs/*.jar
